{
 "title": "Schema Registry cluster",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_schema_registry_registered_count,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Schema Registry Role",
   "type": "stat",
   "description": "The current role of this Schema Registry instance. A value of 1 indicates this instance is the primary, 0 indicates it is a secondary.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_schema_registry_master_slave_role{job=\"schema-registry\",env=\"$env\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Schemas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Schema Registry Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kafka_schema_registry_registered_count{job=\"schema-registry\",env=\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Schema registered over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(schema_type) (kafka_schema_registry_schemas{job=\"schema-registry\",env=\"$env\",instance=~\"$instance\"})",
     "legendFormat": "{{schema_type}}"
    }
   ]
  },
  {
   "title": "Schemas created",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(schema_type)(kafka_schema_registry_schemas{job=\"schema-registry\",env=\"$env\",instance=~\"$instance\"})",
     "legendFormat": "{{schema_type}}"
    }
   ]
  },
  {
   "title": "Schemas deleted",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(schema_type)(kafka_schema_registry_schemas_deleted{job=\"schema-registry\",env=\"$env\",instance=~\"$instance\"})",
     "legendFormat": "{{schema_type}}"
    }
   ]
  },
  {
   "title": "Schemas registered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_schema_registry_registered_count{job=\"schema-registry\",env=\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"schema-registry\",env=\"$env\",instance=~\"$instance\"}[5m])*100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_used_bytes{job=\"schema-registry\",env=\"$env\",instance=~\"$instance\"})",
       "legendFormat": "Used:{{instance}}"
      },
      {
       "expr": "jvm_memory_bytes_max{job=\"schema-registry\",env=\"$env\",area=\"heap\"}",
       "legendFormat": "Max:{{instance}}"
      }
     ]
    },
    {
     "title": "Time spent in GC",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"schema-registry\",env=\"$env\",instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_schema_registry_jetty_metrics_connections_active{job=\"schema-registry\",env=\"$env\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_schema_registry_jersey_metrics_request_rate{job=\"schema-registry\",env=\"$env\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Requests latency 99p",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_schema_registry_jersey_metrics_request_latency_99{job=\"schema-registry\",env=\"$env\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}